container:
    image: gcr.io/bazel-public/bazel:latest
task:
    name: Build the example document
    build_script: bazel build //example:my_report //example:my_dvi_report
task:
    name: Build all package tests
    build_script: bazel build //packages:all
